version: '3.8'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - shared-network
    volumes:
      - ./mysql:/var/lib/mysql

  nextjs:
    build: ./
    container_name: nextjs
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - shared-network
    ports:
      - 3000:3000

networks:
  shared-network:
    driver: bridge
